### PR TITLE
Add tags and date to cards

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Add tags and date to cards

## QA

Run polymer serve then head to http://localhost:8080 and make sure the date (at the top of the tutorial description) and the tags (at the bottom of the description) are both visible and styled in the correct manner as per https://www.dropbox.com/home/00_web_team/_developer.ubuntu.com/dev.ubuntu.com_09_2016/codelabs/exports?preview=Card+-+Style.jpg

Issue https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/7 relates

### CODE REVIEW

**Comment by grahambancroft** [comment]
[Landing page - cards missing detail](https://trello.com/c/HGPwPLUj/2484-landing-page-cards-missing-detail)

**Comment by anthonydillon** [comment]
I didn't see a date. Do I need to run another command to install the new deps? Also on small screens, the tags go under the description text.

ubuntu tutorials

**Comment by WillMoggridge** [comment]
To get the new dependency, please run `bower install` in the source directory.

**Comment by grahambancroft** [comment]
Hi @anthonydillon, sorry, you need to ‘bower install’ to get the date. The height issue is fixed now.

**Pull request merged**
